### ISSUE TITLE
Library now requires requests >= 2.18.0

### ISSUE THREAD

**Issue by nkeriks** [GoogleCloudPlatform/google-resumable-media-python#29]
Hi - this [recent change](https://github.com/GoogleCloudPlatform/google-resumable-media-python/commit/3128765d567d93dc6c0884c0835159647baad6cd) uses the `requests.models.Response` object as a context manager, which is only added in recent versions (>= 2.18.0) of the [requests library](https://github.com/requests/requests/blob/master/HISTORY.rst)

While this is a year old version of requests, it would be good to have this requirement made explicit.  Notably [conda](https://anaconda.org/anaconda/requests) still packages requests 2.14.2 only.

**Comment by dhermes** [comment]
@nkeriks Thanks for bringing this up, we've had similar issues in `google-cloud-python`. Note that this library does not have `requests` as an **explicit** requirement.

@jonparrott WDYT is the right move here?

**Comment by jonparrott** [comment]
Add an optional with requests >= 2.18.0?

**Comment by dhermes** [comment]
@jonparrott Will that enforce the lower bound when users just `pip install google-resumable-media` without the extras.

It's probably worth asking @nkeriks how he came about this realization.

**Comment by nkeriks** [comment]
I had an initialization script that was pip installing various packages (including google cloud python libraries) into a conda python environment. Not the greatest idea in general, but this usually handles dependencies fine.

**Comment by jonparrott** [comment]
No

**Comment by lukesneeringer** [comment]
The optional as well as the fix in google-cloud-python should be sufficient.
