### ISSUE TITLE
Please add the license to the manifest

### ISSUE THREAD

**Issue by johanneskoester** [GoogleCloudPlatform/google-resumable-media-python#8]
Since Apache license has to be shipped with the source, it should be added to the MANIFEST.in file.

xref: conda-forge/staged-recipes#3163

**Comment by dhermes** [comment]
@johanneskoester How does ownership of the conda package work? ISTM that at least one of the actual maintainers of `google-cloud-storage` / `google-resumable-media-python` should be an owner of the Conda package.

/cc @jonparrott 

----

I'm also happy to add the `LICENSE` to the `MANIFEST.in` file. Would you like to send a PR?

**Comment by jonparrott** [comment]
Conda is essentially a downstream packager (like Debian), so it doesn't have to be 1-to-1 with thet upstream owners.

**Comment by johanneskoester** [comment]
No time right now for creating a PR. Of course we would be very happy to have one of you as a contact maintainer. Just let me know if you want to.
